# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1128947476a360f6ed5bf38da79fe662d072cc95205c6ec043e2a68b3e7be22c297347b2004011bbab418957f08df2de9f4eb646251b3f75185b3e18507b54ff
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: kovergenz.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  

test:
  secret_key_base: 8e107d3a03f9951b9b9dc7ae9bcc3fb27a557da96f26393f99168191fb13b741fd4f2d9352b14a1a48ccb6f3e40b68f6c619c2cd652dd7c02f2ea2a9bc911450

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>    
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: kovergenz.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>

